module TargetUsers

let targetUsers = 
    [| "elonmusk"
    ; "schalkdormehl"
    ; "vitalikbuterin"
    ; "zooko"
    ; "ErikVoorhees"
    ; "0xChristina"
    ; "Melt_Dem"
    ; "Permissionless"
    ; "TheFutureisDAO1"
    ; "tayvano_"
    ; "Remi_Tetot"
    ; "ThinkingUSD"
    ; "eitan_levy101"
    ; "runekek"
    ; "Crypto_Texan"
    ; "ethereum"
    ; "MMCrypto"
    ; "1inch"
    ; "opensea"
    ; "sassal0x"
    ; "ThePaulOla"
    ; "AxieInfinity"
    ; "Jihoz_Axie"
    ; "GanQiang5"
    ; "zhusu"
    ; "sancrypt"
    ; "ArbitrumNewsDAO"
    ; "PabloSabbatella"
    ; "Calman16910515"
    ; "Mudit__Gupta"
    ; "MarketingCory"
    ; "TrustlessState"
    ; "WeAreMetaversal"
    ; "santiagoroel"
    ; "RyanSAdams"
    ; "GaIileuGalilei"
    ; "yongkunnn"
    ; "Swagtimus"
    ; "TheCelsian"
    ; "DeFiDiscussion"
    ; "thedailygwei"
    ; "Axie_Queen"
    ; "nixeniego"
    ; "fraxfinance"
    ; "ecomi_rhys"
    ; "CryptoGucci"
    ; "Mandivs"
    ; "0xTycoon"
    ; "screentimes"
    ; "web3degen"
    ; "evan_van_ness"
    ; "DoughDeFi"
    ; "2310_rina"
    ; "DefiMoon"
    ; "KireevArt_NFT"
    ; "DheerajShah_"
    ; "wsdxbz1"
    ; "urahibiki1"
    ; "AxieAur"
    ; "defi_airdrops"
    ; "johnsavage_eth"
    ; "MikeAbundo"
    ; "epnsproject"
    ; "WEFCEO"
    ; "belikewater893"
    ; "CryptoBigot"
    ; "superphiz"
    ; "CPITTIS"
    ; "DCbuild3r"
    ; "FigoETH"
    ; "endeavor54"
    ; "amypeniston"
    ; "CryptoDynasty13"
    ; "officer_cia"
    ; "0xCha0s"
    ; "dimahledba"
    ; "cryptochica_arg"
    ; "Mutant16928"
    ; "kanadelove3"
    ; "CryptoEcon_Li"
    ; "MadYakK"
    ; "das_grasshopper"
    ; "MonetaryWonk"
    ; "0xzak"
    ; "nightmayoralty"
    ; "Layer2News"
    ; "mtnman_eth"
    ; "thefunnyguysNFT"
    ; "regardthefrost"
    ; "LiveLambo"
    ; "FlyGuyInTheSky"
    ; "redlion_news"
    ; "frenchy_707"
    ; "reneil1337"
    ; "MortalCoreSquad"
    ; "AdrianoFeria"
    ; "Darth___ADA"
    ; "0xDamien"
    ; "salmon_crypto"
    ; "xavieriturralde"
    ; "0xcryptowizard"
    ; "Felipefutbol20"
    ; "dorukismen"
    ; "R_Tyler_Smith"
    ; "0xRayan_"
    ; "hotgirltas"
    ; "moneyfox2k"
    ; "GM_NAUCRATIS"
    ; "DeFinalFantasy"
    ; "teslavibes"
    ; "nooz81_eth"
    ; "NHovemann"
    ; "AlexanderFisher"
    ; "cburgdorf"
    ; "fifilechien"
    ; "JoeBGrech"
    ; "valb00"
    ; "gast_25"
    ; "gCAN9k"
    ; "Mark11ETH"
    |]

    // [|"PerfectCNFT"
    // ; "InvisibleBuds"
    // ; "CardanoStonerzC"
    // ; "Kombuchman1"
    // ; "BAYCvoice"
    // ; "Yakuza_Origins"
    // ; "Moneymike_813"
    // ; "VeggieMatesNFT"
    // ; "CNFT_Dice"
    // ; "DegenToonz"
    // ; "DeepVisionNFTs"
    // ; "CnftWorld"
    // ; "TB_BladeZ"
    // ; "BabyAlienClub"
    // ; "ADANinjaz"
    // ; "adaGOATS"
    // ; "CryptoverseCNFT"
    // ; "CryptoVivid"
    // ; "Wh1sper_Will0w"
    // ; "Brandonisawful"
    // ; "peeps_crypto"
    // ; "NinjameZ_Bond"
    // ; "OlympLor"
    // ; "gcuriom"
    // ; "NicoOnselen"
    // ; "zushanhashmi"
    // ; "PlanetKrom"
    // ; "berry_ales"
    // ; "BadgerSalesman"
    // ; "edwintax1"
    // ; "CalvinsBrew"
    // ; "PsVEagle"
    // |]

let ecommerceUsers =
    [| "syahmi_ahmad"
    ; "hafizazman_co"
    ; "revistacodigo21"
    ; "sheni_coker"
    ; "TohruAIO_"
    ; "amjsutherland"
    ; "BillDA"
    ; "fmomboisse"
    ; "simeta_io"
    ; "teepusahab"
    ; "PocketPayFin"
    ; "KimwiNews"
    ; "RogerPareraWM"
    ; "m0d0"
    ; "ecomchasedimond"
    ; "DanielMoldawsky"
    ; "DimitriHommel"
    ; "Chronopost"
    ; "aneeshnair"
    ; "ultradavid"
    ; "IXRPWORLD"
    ; "OlMktgPro"
    ; "storex_"
    ; "iamimanuel"
    ; "Blu_Digital"
    ; "UPS_FR"
    ; "EddyGarciaVega"
    ; "ecuestre_"
    ; "danbarker"
    ; "_SandraSM_"
    ; "muhemmedasfand"
    ; "ccmarce_writes"
    ; "bitshopee_com"
    ; "conqoer"
    ; "ClaudeCalmes"
    ; "ANDRW3J"
    ; "BriannaAhearn"
    ; "DaveLeeFT"
    ; "MrRichProfessor"
    ; "SyedAbbasRizz"
    ; "MaRiEen2M"
    ; "EmarketerzFR"
    ; "ThisIs_M1nH"
    ; "EnterpriseB2B"
    ; "touitou_david"
    ; "calvo_virginia"
    ; "AbbieReal"
    ; "styledo"
    ; "discerningdmain"
    ; "TalOfer"
    ; "marinamval"
    ; "KrAbhinavGupta"
    ; "yvahn"
    ; "Allegro_Group"
    ; "SharifaAlBarami"
    ; "gemprojecmarket"
    ; "kmanish_"
    ; "woodemia"
    ; "amolleda"
    ; "MelissaSulewski"
    ; "eqhq"
    ; "Distribucionyma"
    ; "PS_Informatique"
    ; "rogersantenac"
    ; "BourerTheFunk"
    ; "Geoff1of1"
    ; "nirxcoin"
    ; "PrisyncCom"
    ; "scabbiamx"
    ; "dazz0_716"
    ; "malsimons"
    ; "PepEstepa"
    ; "DinoVedo"
    ; "hannahbethstyle"
    ; "lorigeishecker"
    ; "livehappy8"
    ; "lolilme"
    ; "apeiroxcom"
    ; "RodneyPER"
    ; "AaronOrendorff"
    ; "sandyhussain"
    ; "patricia_haag"
    ; "paulygoo"
    ; "spencerhudson"
    ; "ViperAIO_"
    ; "Rinaldeens"
    ; "LYBObiz"
    ; "GingerAttaway"
    ; "IvanOB_Oficial"
    ; "BorjaDM_"
    ; "SchumacherFM"
    ; "menottimena"
    ; "social_savannah"
    ; "tanotopp"
    ; "BigCommerce"
    ; "TraceWall"
    ; "ScottThomps74"
    ; "Texas_Steve_Blu"
    ; "vegardwikeby"
    ; "IrishEcom"
    |]

let effUsers =
    [|"SL_Thethwayo" 
    ; "Julius_S_Malema"
    ; "MbuyiseniNdlozi"
    ; "gm_mhlongo"
    ; "anildash"
    ; "54Battalion"
    ; "evacide"
    ; "SuzCrimi"
    ; "AreOhEssEyeEe"
    ; "veronica_mente"
    ; "FloydShivambu"
    ; "Tyrone_Mkansi"
    ; "Sinawo_Thambo"
    ; "lenazun"
    ; "SixoGcilishe"
    ; "TheNostalgicCo"
    ; "jilliancyork"
    ; "HhMkhaliphi"
    ; "OmphileMaotwe"
    ; "Ta_Fitty"
    ; "MathibeRebecca"
    ; "EFFWesternCape_"
    ; "vuyanipambo"
    ; "erikmackenzie"
    ; "YolzYako"
    ; "KP11Studios"
    ; "vusumuzikhoza"
    ; "tarah"
    ; "nellucnhoj"
    ; "bcrypt"
    ; "DiaKayyali"
    ; "enn_nafnlaus"
    ; "MTshwaku"
    ; "EffRonny"
    ; "Konducta4LFE"
    ; "sfmnemonic"
    ; "Leeds_Untied"
    ; "k_trendacosta"
    ; "Eskiworks"
    ; "RandGallery"
    ; "Alexand85266011"
    ; "nappy_techie"
    ; "mafiwa2"
    ; "Edenza"
    ; "EFFStudents"
    ; "HubieCumberdale"
    ; "RotVanRotterdam"
    ; "BassilSabelo"
    ; "tinydancer0318"
    ; "SwartzCr"
    ; "JacksonWinslow3"
    ; "mbarc52"
    ; "Sanc_SA"
    ; "EFF_FreeState"
    ; "k_u_m_a_r_u_n"
    ; "Matlho53"
    ; "malaikafraley"
    ; "ZweSibiya"
    ; "Triggs390"
    ; "ronnie_kobe88"
    ; "zittrain"
    ; "anthonykava"
    ; "FighterKamza"
    ; "danielnazer"
    ; "Simza_396225"
    ; "EikoSmid"
    ; "IanStewartVital"
    ; "mkoo7gp"
    ; "KatieReyn2511"
    ; "Wisqerbisqit"
    ; "SodiyePetha"
    ; "peacey_queen"
    ; "MosaRoccoII"
    ; "ReneMalika2"
    ; "marciahofmann"
    ; "JustiThabelo"
    ; "Some_SheeShee"
    ; "tracyvegas"
    ; "Sbu_Fo"
    ; "10thcard"
    ; "giulseffe_"
    ; "mguariglia"
    ; "PhathutshedzoM7"
    ; "tkh16"
    ; "kurtopsahl"
    ; "MatthewsMahlubi"
    ; "mailola_poppy"
    ; "Resilience_FK"
    ; "EFF_Cape_Metro"
    ; "husknoises"
    ; "bsletten"
    ; "tebza_e"
    ; "jayceahthebe"
    ; "bidetofevil"
    ; "megangrA"
    ; "cooperq"
    ; "AngelStar254"
    ; "JohnJChase1"
    ; "mcarlingoldberg"
    ; "NaSh12"
    |]